# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wordless
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: wordlesss-backend-rest-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: wordless-backend-rest-api

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    EMOTE_REACTION_TABLE: emote-reaction-table-${sls:stage}
    USERS_TABLE: users-table-${sls:stage}
    DEPLOY_ENV: ${sls:stage}
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    FRONTEND_URL: ${self:custom.frontend-url.${sls:stage}}
    ALLOW_ORIGIN: ${self:custom.frontend-url.offline}
  # 初回実行時はコメントアウトする
  apiName: wordless-backend-rest-api-${sls:stage}

functions:
  getUserHandler:
    handler: app/users/findUser.findUser
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true
    vpc:
      securityGroupIds: ${self:custom.security-group-id.${sls:stage}}
      subnetIds: ${self:custom.vpc_subnet_id.${sls:stage}}
  fetchEmotes:
    handler: app/emotes/fetchEmotes.fetchEmotes
    events:
      - http:
          path: emotes/
          method: get
          cors: true
    vpc:
      securityGroupIds: ${self:custom.security-group-id.${sls:stage}}
      subnetIds: ${self:custom.vpc_subnet_id.${sls:stage}}

resources:
  Conditions:
    IsOffline: !Equals ["${sls:stage}", "offline"]
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: users-table-${sls:stage}
    EmoteReactionTable:
      Type: AWS::DynamoDB::Table
      Condition: IsOffline
      Properties:
        AttributeDefinitions:
          - AttributeName: emoteReactionId
            AttributeType: S
        KeySchema:
          - AttributeName: emoteReactionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: emote-reaction-table-${sls:stage}

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  security-group-id:
    offline: ${env:VPC_SECURITY_GROUP_ID}
    dev: ${env:VPC_SECURITY_GROUP_ID}
    prod: ${env:VPC_SECURITY_GROUP_ID}
  vpc_subnet_id:
    offline: ${env:VPC_SUBNET_ID}
    dev: ${env:VPC_SUBNET_ID}
    prod: ${env:VPC_SUBNET_ID}
  frontend-url:
    offline: http://localhost:3000
    dev: https://develop.d2k4f3iskqkv6l.amplifyapp.com
    prod: https://main.d2k4f3iskqkv6l.amplifyapp.com
  serverless-dynamodb:
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    
    seed:
      dev:
        sources:
          - table: users-table-offline
            sources: [./seed/users-table-offline.json]
          - table: emote-reaction-table-offline
            sources: [./seed/emote-reaction-table-offline.json]
