# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wordless
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: wordlesss-backend-rest-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: wordless-backend-rest-api

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    DEPLOY_ENV: ${sls:stage}
  apiName: wordless-backend-rest-api-${sls:stage}

functions:
  getUserHandler:
    handler: app/users/handler.getUserHandler
    events:
      - http:
          path: users/{userId}
          method: get
          cors:
            origins: 
              - ${self:custom.frontendUrl.${sls:stage}} 
            methods:
              - GET

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  frontendUrl:
    offline: http://localhost:3000/
    dev: https://develop.d2k4f3iskqkv6l.amplifyapp.com/
    prod: https://main.d2k4f3iskqkv6l.amplifyapp.com/
  serverless-dynamodb:
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    
    seed:
      dev:
        sources:
          - table: users-table-offline
            sources: [./seed/users-table-offline.json]
